[[main]]
  name = "主页"
  url = "/"
  weight = 10

[[main]]
  name = "博客"
  url = "/blog/"
  weight = 20

[[main]]
  name = "标签"
  url = "/tags/"
  weight = 30

[[main]]
  name = "文档"
  url = "https://docs.futurelog.xyz"
  weight = 40

[[main]]
  name = "项目"
  url = "/projects/"
  weight = 50

[[main]]
  name = "Sample project"
  url = "/projects/sample-project/"
  parent = "项目"
  weight = 1

[[main]]
  name = "Another project"
  url = "/projects/another-project/"
  parent = "项目"
  weight = 2

[[main]]
  name = "关于"
  url = "/about/"
  weight = 60


[[social]]
  name = "LinkedIn"
  pre = "<i class=\"fab fa-linkedin fa-2x\"></i>"
  url = "https://linkedin.com/"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "<i class=\"fab fa-github fa-2x\"></i>"
  url = "https://github.com/"
  weight = 20

[[social]]
  name = "Medium"
  pre = "<i class=\"fab fa-medium fa-2x\"></i>"
  url = "https://medium.com/"
  weight = 30

[[sample]]
  name = "Blog"
  url = "/blog/"
  weight = 10

[[sample]]
  name = "Projects"
  url = "/projects/"
  weight = 20

[[sample]]
  name = "Sample project"
  url = "/projects/sample-project/"
  parent = "Projects"
  weight = 1

[[sample]]
  name = "Another project"
  url = "/projects/another-project/"
  parent = "Projects"
  weight = 2
  

[[footer]]
  name = "Links"
  weight = 10

[[footer]]
  parent = "Links"
  name = "Home"
  pageRef = "/"
  weight = 10

[[footer]]
  parent = "Links"
  name = "About"
  pageRef = "/about/"
  weight = 20
  [footer.params]
    alias = true

[[footer]]
  parent = "Links"
  name = "Docs"
  pageRef = "https://docs.futurelog.xyz"
  weight = 30

[[footer]]
  name = "Community"
  weight = 20

[[footer]]
  parent = "Community"
  name = "Github"
  url = "https://github.com/wallezen"
  weight = 10

[[footer]]
  parent = "Community"
  name = "Twitter"
  url = "https://twitter.com/wallezen007"
  weight = 20
